name: Deployment (dev)

concurrency:
  group: development
  cancel-in-progress: true
  
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        
    - uses: actions/setup-node@v4
      with:
        cache: 'npm'
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
        
    - name: Install Composer Dependencies
      uses: php-actions/composer@v6
      with:
        quiet: yes
        args: --no-ansi --no-scripts --prefer-dist
      
    - name: Install Node Dependencies
      run: npm ci
      
    - name: Build via Vite
      run: npm run build
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
        
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
      
  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.forge_ssh_private_key }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install Forge CLI
        run: composer global require laravel/forge-cli
      - name: Deploy via Forge CLI
        run: |
          forge server:switch ${{ vars.DEPLOY_SERVER_NAME }} && \
          forge deploy ${{ vars.DEPLOY_SITE_NAME }}
        env:
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
