name: Deployment (dev)

concurrency:
  group: development
  cancel-in-progress: true
  
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        
    - uses: actions/setup-node@v4
        
    - uses: actions/checkout@v4
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Install Node Dependencies
      run: npm ci
      
    - name: Build via Vite
      run: npm run build
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
        
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
      
  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_type: 'form-urlencoded'
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          data: 'forge_deploy_branch=${{ github.ref }}&forge_deploy_commit=${{ github.sha }}&forge_deploy_author=${{ github.actor }}'
